youtube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('youtubeapp.urls'))
]

youtubeapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'ytproject'


urlpatterns = [
    path('', views.index , name = 'home'),
    path('download/', views.download , name = 'download'),
    path('download/<itag>', views.yt_download_done , name = 'download_done'),
    path('download/<itag>', views.yt_mp3download_done , name = 'mp3download_done')
]

youtubeapp/models.py
from django.db import models

# Create your models here.

youtubeapp/views.py
from django.shortcuts import render
from pytube import YouTube
import os


# Create your views here.
def index(request):
    return render(request,'index.html')

def download(request):
    global url
    global title
    url = request.GET['url']
    yt = YouTube(str(url))
    video = []
    audio = []
    video = yt.streams.filter(progressive=True).all()
    audio  = yt.streams.filter(only_audio=True).all()
    # print(audio)
    embed_link = url.replace("watch?v=","embed/")
    title = yt.title
    thumb = yt.thumbnail_url
    # print(thumb)

    context = {'video': video ,'audio': audio, 'embed' : embed_link ,'bg':thumb, 'title': title}
    # context2 = { , 'embed' : embed_link , 'title': title}
    # ,
    
    return render(request,'download.html', context )

def yt_download_done(request,itag):
    global url
    homedir  = os.path.expanduser("~")
    dirs = homedir + '/Downloads'
    if request.method == "POST":  
        temp = YouTube(url).streams.get_by_itag(int(itag))
        # print(temp)
        # if temp.type() == "audio/mpeg"
        YouTube(url).streams.get_by_itag(int(itag)).download(dirs)
        return render(request,'done.html', {'tit':title})
    else:
        return render(request,'error.html', {'tit':title})

def yt_mp3download_done(request,itag):
    global url
    homedir  = os.path.expanduser("~")
    dirs = homedir + '/Downloads'
    if request.method == "POST":
        out_file = YouTube(url).streams.get_by_itag(int(itag)).download(dirs)
        # print(out_file)
        base, ext = os.path.splitext(out_file)
        new_file = base + '.mp3'
        os.rename(out_file, new_file)
        return render(request,'done.html', {'tit':title})
    else:
        return render(request,'error.html', {'tit':title})

youtubeapp/templates/done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Done</title>
    <style>
        giphy{
            margin-top: 10cm;
        }
    </style>
</head>
<body>
    <center>
        <h1>{{tit}} has been downloaded suscessfully <br>
        Check your Download folder</h1>
        <img src= {% static '/static/animation_500_knwt5i5x.gif'  %} alt="">
        
        
    </center>


</body>
</html>

youtubeapp/templates/download.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>YouTube Downloader</title>
    <style>
      body{
        background-color: rgb(232, 255, 254);
      }
    </style>
  </head>
  <body>
    <!-- nav bar starts -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
      <a class="navbar-brand" href="#">YouTube Downloader</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://itsmearghya.blogspot.com/">PortFolio</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Contact me ?
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="https://www.instagram.com/arghya_tlf/">Instagram</a>
              <a class="dropdown-item" href="https://www.linkedin.com/in/arghyadev-sarkar/">LinkedIn</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something More ??</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <!-- navbar ends  -->
    <div  class="bg_img"></div>

    <!-- main body starts -->
    <div class="container">
        <h1 class="mt-5">

            Video Title : {{title}}
        </h1>
        <div class=" my-5 embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src={{embed}} allowfullscreen></iframe>
        </div>
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Size</th>
                <th scope="col">Quality</th>
                <th scope="col">Fps</th>
                <th scope="col">Type</th>
                <th scope="col">Download</th>
              </tr>
            </thead>
              {% for j in video %}
            <tbody>
              <tr>
                <th>{{j.filesize}} bytes</th>
                <td>{{j.resolution}}</td>
                <td>{{j.fps}}</td>
                <td>{{j.type}}</td>

                <td>
                    <form action="{% url 'ytproject:download_done' j.itag %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" onclick="clicked()" class="btn btn-success" value="Download">
                    </form>
                </td>
              </tr>
            </tbody>
              {% endfor %}
        </table>
            
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Size</th>
              <th scope="col">Quality</th>
              <th scope="col">Type</th>
              <th scope="col">itag</th>
              <th scope="col">Download</th>
            </tr>
          </thead>
          {% comment %} <h2>Currently Mp3 Section isn't working.. Will be live  soon</h2> {% endcomment %}
            {% for j in audio %} 
          <tbody>
            <tr>
              <th>{{j.filesize}} bytes</th>
              <td>{{j.abr}}</td>
              <td>{{j.type}}</td>
              <td>{{j.itag}}</td>
              <td>
                <form action="{% url 'ytproject:mp3download_done' j.itag %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" onclick="clicked()" class="btn btn-success" value="Download">
                </form>
            </td>
            </tr>
          </tbody>
            {% endfor %}
        </table>  

              

           
    </div>

    <script>
      function clicked(){
        alert("Your Video has been Downloading.. Wait Until next page arrives");
      }
    </script>

    <!-- main body ends  -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <center>
      <p>© Designed by <strong>Arghya</strong> <script>document.write(new Date().getFullYear())</script>    
      <span>• </span> 

    </center>

  </body>
</html>

youtubeapp/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Something Wrong</title>
    <style>
        giphy{
            margin-top: 10cm;
        }
    </style>
</head>
<body>
    <center>
        <h1>
            Error , Try Again
        </h1>
    </center>


    
</body>
</html>

youtubeapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>YouTube Downloader</title>
    <style>
      body{
        background-color: rgb(218, 229, 250);
        
      }
    </style>
  </head>
  <body>
    <!-- nav bar starts -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">YouTube Downloader</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://itsmearghya.blogspot.com/">PortFolio</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Contact me ?
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="https://www.instagram.com/arghya_tlf/">Instagram</a>
                <a class="dropdown-item" href="https://www.linkedin.com/in/arghyadev-sarkar/">LinkedIn</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something More ??</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0"  action="http://www.youtube.com/results" method="get" target="_blank" >
            <input class="form-control mr-sm-2" placeholder="Search in YouTube" aria-label="Search" name="search_query" type="text" maxlength="128"   >
            <select name="search_type">
            <option value="">Videos</option>
            <option value="search_users">Channels</option>
            </select>
            <input type="submit" value="Search" />
          </form>
        </div>
      </nav>


    <!-- navbar ends  -->
     

    <!-- main body starts -->
    <div class="bg-image"></div>
    <div class="mt-5">
        <center><h1 style="font-family: Georgia, 'Times New Roman', Times, serif;" ><strong>Enter YouTube URL</strong></h1></center>
    </div>
    <div class="container mt-5">
        <center>
            <form action="download/" method="GET">
                <div class="form-group">
                  <input name="url" type="text" class="form-control"  placeholder="Enter Youtube Url">       
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </center>

    </div>


    <!-- main body ends  -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <center>
      <p>© Designed by <strong>Arghya</strong> <script>document.write(new Date().getFullYear())</script>    
      <span>• </span> 

    </center>
  </body>
</html>